// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlBz7NzpUzdCYTxnfHss658IhM06OB2fA',
    appId: '1:512979344824:web:d6862a0a9a3693d1d8034d',
    messagingSenderId: '512979344824',
    projectId: 'bulletin-board-d6754',
    authDomain: 'bulletin-board-d6754.firebaseapp.com',
    storageBucket: 'bulletin-board-d6754.appspot.com',
    measurementId: 'G-W6KSBTXRX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYq9_AnRhgqPt6_uU8d30p3S0aVVTbeG4',
    appId: '1:512979344824:android:b08dd522be2a62bcd8034d',
    messagingSenderId: '512979344824',
    projectId: 'bulletin-board-d6754',
    storageBucket: 'bulletin-board-d6754.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbjh0VlVi0hXVtukaltOEwUXCUHwOUtNs',
    appId: '1:512979344824:ios:54943dd4b75c0546d8034d',
    messagingSenderId: '512979344824',
    projectId: 'bulletin-board-d6754',
    storageBucket: 'bulletin-board-d6754.appspot.com',
    iosBundleId: 'com.example.bulletinBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbjh0VlVi0hXVtukaltOEwUXCUHwOUtNs',
    appId: '1:512979344824:ios:f709fb1222866cd5d8034d',
    messagingSenderId: '512979344824',
    projectId: 'bulletin-board-d6754',
    storageBucket: 'bulletin-board-d6754.appspot.com',
    iosBundleId: 'com.example.bulletinBoard.RunnerTests',
  );
}
